"""t

Revision ID: 05da557cc842
Revises: 394dced522e3
Create Date: 2021-10-20 17:59:28.210939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05da557cc842'
down_revision = '394dced522e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
