"""t

Revision ID: 394dced522e3
Revises: 4d6b9f926cbd
Create Date: 2021-10-20 17:51:36.471713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '394dced522e3'
down_revision = '4d6b9f926cbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
