"""ta

Revision ID: 4d6b9f926cbd
Revises: 6382fd7703df
Create Date: 2021-10-20 17:46:24.192973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d6b9f926cbd'
down_revision = '6382fd7703df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
