"""New

Revision ID: 6c3a805288fb
Revises: 05da557cc842
Create Date: 2021-10-22 22:48:33.600396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c3a805288fb'
down_revision = '05da557cc842'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
