"""New

Revision ID: f17d96bfa549
Revises: 6c3a805288fb
Create Date: 2021-10-22 22:51:05.988741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f17d96bfa549'
down_revision = '6c3a805288fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_project_id', table_name='project')
    op.drop_table('project')
    op.drop_index('ix_task_id', table_name='task')
    op.drop_table('task')
    op.drop_index('ix_column_id', table_name='column')
    op.drop_table('column')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('column',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('project', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['project'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_column_id', 'column', ['id'], unique=False)
    op.create_table('task',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('text', sa.VARCHAR(), nullable=True),
    sa.Column('column', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['column'], ['column.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_task_id', 'task', ['id'], unique=False)
    op.create_table('project',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('admin', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['admin'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_project_id', 'project', ['id'], unique=False)
    # ### end Alembic commands ###
